---
new_page_extension: md
auto_deploy: false
admin_path: "/werkbank"
webhook_url: 
sections:
- type: directory
  path: team
  label: Team
  create: all
  match: "*.md"
- type: document
  path: index.md
  label: Home
- type: directory
  path: termine
  label: Kalender
  create: documents
  match: "*.md"
  new_doc_ext: md
- type: document
  path: forschungsraum.md
  label: Forschungsraum
- type: document
  path: next-level.md
  label: Next Level
- type: document
  path: freisinn.md
  label: Freisinn
- type: document
  path: coaching.md
  label: Coaching
- type: document
  path: projekte-workshops.md
  label: Projekte Workshops
- type: document
  path: impressum.md
  label: Impressum
upload_dir: assets/uploads
public_path: _site/assets/uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: "/drafts"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
