---
new_page_extension: md
auto_deploy: false
admin_path: "/werkbank"
webhook_url: 
sections:
- type: document
  path: index.md
  label: Home
- type: document
  path: forschungsraum.md
  label: Forschungsraum
  match: "**/*"
- type: document
  path: next-level.md
  label: Next Level
  match: "**/*"
- type: document
  path: freisinn.md
  label: Freisinn
  match: "**/*"
- type: document
  path: coaching.md
  label: Coaching
  match: "**/*"
- type: document
  path: projekte-workshops.md
  label: Projekte Workshops
  match: "**/*"
upload_dir: uploads
public_path: _site/uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: "/drafts"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
